export const SETHEADCONFIG = 'setHeadConfig'
export const ADD = 'add'
export const SQUARE = 'square'
export const SHOW_MESSAGE_RECORD_APPLICATION = 'SHOW_MESSAGE_RECORD_APPLICATION'
export const SET_ARGU = 'SET_ARGU'